.TH "lib_bfr/src/object Directory Reference" 3 "Wed Apr 7 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/object Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBclan\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplayer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsecretObjective\&.cpp\fP"
.br
.in -1c
