.TH "lib_bfr/include/lib_bfr/object Directory Reference" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/lib_bfr/object Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcard\&.h\fP"
.br
.ti -1c
.RI "file \fBclan\&.h\fP"
.br
.ti -1c
.RI "file \fBplayer\&.h\fP"
.br
.ti -1c
.RI "file \fBsecretObjective\&.h\fP"
.br
.in -1c
