.TH "lib_bfr/src/karta Directory Reference" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/karta Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBborder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmap\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprovince\&.cpp\fP"
.br
.ti -1c
.RI "file \fBterritory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtokenBasement\&.cpp\fP"
.br
.in -1c
