.TH "battle_for_rokugan::karta::Border" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::karta::Border
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <border\&.h>\fP
.PP
Inherits \fBbattle_for_rokugan::karta::TokenBasement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBorder\fP (\fBProvince\fP *prov, QObject *parent)"
.br
.ti -1c
.RI "\fBBorder\fP (\fBProvince\fP *prov1, \fBProvince\fP *prov2, QObject *parent)"
.br
.ti -1c
.RI "\fBBorderType\fP \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBsetType\fP (\fBBorderType\fP \fBtype\fP)"
.br
.ti -1c
.RI "\fBtoken::Combat\fP * \fBcombatToken\fP () const"
.br
.ti -1c
.RI "virtual void \fBpushCombatToken\fP (\fBtoken::Combat\fP *token) override final"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBProvince\fP * \fBprovince1\fP () const"
.br
.ti -1c
.RI "\fBProvince\fP * \fBprovince2\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBorderType\fP \fBm_type\fP"
.br
.ti -1c
.RI "\fBProvince\fP * \fBm_province1\fP"
.br
.ti -1c
.RI "\fBProvince\fP * \fBm_province2\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBhandler::Battle\fP"
.br
.ti -1c
.RI "class \fBkarta::Province\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file border\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "battle_for_rokugan::karta::Border::Border (\fBProvince\fP * prov, QObject * parent)"

.PP
Definition at line 4 of file border\&.cpp\&.
.SS "battle_for_rokugan::karta::Border::Border (\fBProvince\fP * prov1, \fBProvince\fP * prov2, QObject * parent)"

.PP
Definition at line 11 of file border\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void battle_for_rokugan::karta::Border::clear ()"

.PP
Definition at line 51 of file border\&.cpp\&.
.SS "bfr::token::Combat * battle_for_rokugan::karta::Border::combatToken () const"

.PP
Definition at line 21 of file border\&.cpp\&.
.SS "bfr::karta::Province * battle_for_rokugan::karta::Border::province1 () const"

.PP
Definition at line 18 of file border\&.cpp\&.
.SS "bfr::karta::Province * battle_for_rokugan::karta::Border::province2 () const"

.PP
Definition at line 19 of file border\&.cpp\&.
.SS "void battle_for_rokugan::karta::Border::pushCombatToken (\fBtoken::Combat\fP * token)\fC [final]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBbattle_for_rokugan::karta::TokenBasement\fP\&.
.PP
Definition at line 44 of file border\&.cpp\&.
.SS "void battle_for_rokugan::karta::Border::setType (\fBBorderType\fP type)"

.PP
Definition at line 37 of file border\&.cpp\&.
.SS "\fBbfr::BorderType\fP battle_for_rokugan::karta::Border::type () const"

.PP
Definition at line 28 of file border\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBhandler::Battle\fP\fC [friend]\fP"

.PP
Definition at line 30 of file border\&.h\&.
.SS "friend class \fBkarta::Province\fP\fC [friend]\fP"

.PP
Definition at line 31 of file border\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBProvince\fP* battle_for_rokugan::karta::Border::m_province1\fC [private]\fP"

.PP
Definition at line 27 of file border\&.h\&.
.SS "\fBProvince\fP* battle_for_rokugan::karta::Border::m_province2\fC [private]\fP"

.PP
Definition at line 28 of file border\&.h\&.
.SS "\fBBorderType\fP battle_for_rokugan::karta::Border::m_type\fC [private]\fP"

.PP
Definition at line 26 of file border\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
