.TH "battle_for_rokugan::karta" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::karta
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBorder\fP"
.br
.ti -1c
.RI "class \fBMap\fP"
.br
.ti -1c
.RI "class \fBProvince\fP"
.br
.ti -1c
.RI "class \fBTerritory\fP"
.br
.ti -1c
.RI "class \fBTokenBasement\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
