.TH "battle_for_rokugan::handler" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::handler
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattle\fP"
.br
.ti -1c
.RI "class \fBStats\fP"
.br
.ti -1c
.RI "class \fBTurn\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
