.TH "battle_for_rokugan::token" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::token
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCombat\fP"
.br
.ti -1c
.RI "class \fBControl\fP"
.br
.ti -1c
.RI "class \fBHonor\fP"
.br
.ti -1c
.RI "class \fBProvince\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
