.TH "battle_for_rokugan::token::Control" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::token::Control
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControl\fP (bool \fBisOn\fP, \fBClanType\fP clan, QObject *parent)"
.br
.ti -1c
.RI "bool \fBisOn\fP () const"
.br
.ti -1c
.RI "uint \fBdefends\fP () const"
.br
.ti -1c
.RI "uint \fBstars\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_isOn\fP"
.br
.ti -1c
.RI "\fBClanType\fP \fBm_clan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file control\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "battle_for_rokugan::token::Control::Control (bool isOn, \fBClanType\fP clan, QObject * parent)"

.PP
Definition at line 3 of file control\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint battle_for_rokugan::token::Control::defends () const"

.PP
Definition at line 14 of file control\&.cpp\&.
.SS "bool battle_for_rokugan::token::Control::isOn () const"

.PP
Definition at line 9 of file control\&.cpp\&.
.SS "uint battle_for_rokugan::token::Control::stars () const"

.PP
Definition at line 19 of file control\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBClanType\fP battle_for_rokugan::token::Control::m_clan\fC [private]\fP"

.PP
Definition at line 20 of file control\&.h\&.
.SS "bool battle_for_rokugan::token::Control::m_isOn\fC [private]\fP"

.PP
Definition at line 19 of file control\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
