.TH "battle_for_rokugan::object::SecretObjective" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::object::SecretObjective
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <secretObjective\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecretObjective\fP (\fBSecretObjectiveType\fP \fBtype\fP, \fBkarta::Map\fP *map, \fBhandler::Stats\fP *stats, QObject *parent)"
.br
.ti -1c
.RI "QString \fBname\fP ()"
.br
.ti -1c
.RI "QString \fBdescription\fP ()"
.br
.ti -1c
.RI "int \fBresult\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBdescription\fP () const"
.br
.ti -1c
.RI "\fBSecretObjectiveType\fP \fBtype\fP () const"
.br
.ti -1c
.RI "bool \fBpicked\fP () const"
.br
.ti -1c
.RI "void \fBsetPicked\fP (\fBClan\fP *clan)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBresult\fP (\fBSecretObjectiveType\fP \fBtype\fP, \fBClan\fP *clan, \fBkarta::Map\fP *map, \fBhandler::Stats\fP *stats)"
.br
.ti -1c
.RI "static QString \fBname\fP (\fBSecretObjectiveType\fP \fBtype\fP)"
.br
.ti -1c
.RI "static QString \fBdescription\fP (\fBSecretObjectiveType\fP \fBtype\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSecretObjectiveType\fP \fBm_type\fP"
.br
.ti -1c
.RI "\fBClan\fP * \fBm_clan\fP"
.br
.ti -1c
.RI "bool \fBm_picked\fP"
.br
.ti -1c
.RI "\fBkarta::Map\fP * \fBm_map\fP"
.br
.ti -1c
.RI "\fBhandler::Stats\fP * \fBm_stats\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file secretObjective\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "battle_for_rokugan::object::SecretObjective::SecretObjective (\fBSecretObjectiveType\fP type, \fBkarta::Map\fP * map, \fBhandler::Stats\fP * stats, QObject * parent)"

.PP
Definition at line 11 of file secretObjective\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString battle_for_rokugan::object::SecretObjective::description ()"

.PP
Definition at line 145 of file secretObjective\&.cpp\&.
.SS "QString battle_for_rokugan::object::SecretObjective::description () const"

.SS "QString battle_for_rokugan::object::SecretObjective::description (\fBSecretObjectiveType\fP type)\fC [static]\fP"

.PP
Definition at line 146 of file secretObjective\&.cpp\&.
.SS "QString battle_for_rokugan::object::SecretObjective::name ()"

.PP
Definition at line 125 of file secretObjective\&.cpp\&.
.SS "QString battle_for_rokugan::object::SecretObjective::name () const"

.SS "QString battle_for_rokugan::object::SecretObjective::name (\fBSecretObjectiveType\fP type)\fC [static]\fP"

.PP
Definition at line 126 of file secretObjective\&.cpp\&.
.SS "bool battle_for_rokugan::object::SecretObjective::picked () const"

.PP
Definition at line 23 of file secretObjective\&.cpp\&.
.SS "int battle_for_rokugan::object::SecretObjective::result () const"

.PP
Definition at line 36 of file secretObjective\&.cpp\&.
.SS "int battle_for_rokugan::object::SecretObjective::result (\fBSecretObjectiveType\fP type, \fBClan\fP * clan, \fBkarta::Map\fP * map, \fBhandler::Stats\fP * stats)\fC [static]\fP"

.PP
Definition at line 37 of file secretObjective\&.cpp\&.
.SS "void battle_for_rokugan::object::SecretObjective::setPicked (\fBClan\fP * clan)"

.PP
Definition at line 28 of file secretObjective\&.cpp\&.
.SS "\fBbfr::SOT\fP battle_for_rokugan::object::SecretObjective::type () const"

.PP
Definition at line 18 of file secretObjective\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBClan\fP* battle_for_rokugan::object::SecretObjective::m_clan\fC [private]\fP"

.PP
Definition at line 34 of file secretObjective\&.h\&.
.SS "\fBkarta::Map\fP* battle_for_rokugan::object::SecretObjective::m_map\fC [private]\fP"

.PP
Definition at line 36 of file secretObjective\&.h\&.
.SS "bool battle_for_rokugan::object::SecretObjective::m_picked\fC [private]\fP"

.PP
Definition at line 35 of file secretObjective\&.h\&.
.SS "\fBhandler::Stats\fP* battle_for_rokugan::object::SecretObjective::m_stats\fC [private]\fP"

.PP
Definition at line 37 of file secretObjective\&.h\&.
.SS "\fBSecretObjectiveType\fP battle_for_rokugan::object::SecretObjective::m_type\fC [private]\fP"

.PP
Definition at line 33 of file secretObjective\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
