.TH "battle_for_rokugan::object" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::object
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCard\fP"
.br
.ti -1c
.RI "class \fBClan\fP"
.br
.ti -1c
.RI "class \fBPlayer\fP"
.br
.ti -1c
.RI "class \fBSecretObjective\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
