.TH "battle_for_rokugan::token::Honor" 3 "Wed Apr 7 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battle_for_rokugan::token::Honor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <honor\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHonor\fP (uint value, QObject *parent)"
.br
.ti -1c
.RI "uint \fBhonor\fP () const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uint \fBm_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file honor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "battle_for_rokugan::token::Honor::Honor (uint value, QObject * parent)"

.PP
Definition at line 3 of file honor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint battle_for_rokugan::token::Honor::honor () const"

.PP
Definition at line 9 of file honor\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint battle_for_rokugan::token::Honor::m_value\fC [private]\fP"

.PP
Definition at line 16 of file honor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
