.TH "lib_bfr/src/handler/battle.cpp" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/handler/battle.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/handler/battle\&.h'\fP
.br
\fC#include 'lib_bfr/karta/border\&.h'\fP
.br
\fC#include 'lib_bfr/karta/map\&.h'\fP
.br
\fC#include 'lib_bfr/karta/province\&.h'\fP
.br
\fC#include 'lib_bfr/karta/territory\&.h'\fP
.br
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_bfr/token/combat\&.h'\fP
.br
\fC#include 'lib_bfr/token/province\&.h'\fP
.br
\fC#include <QtCore/QMap>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
