.TH "lib_bfr/include/bfrEnum.h" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/bfrEnum.h
.SH SYNOPSIS
.br
.PP
\fC#include <optional>\fP
.br
\fC#include <QtCore/QList>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< CardType > \fBbattle_for_rokugan::CardTypeList\fP"
.br
.ti -1c
.RI "typedef std::optional< ClanType > \fBbattle_for_rokugan::ClanTypeOpt\fP"
.br
.ti -1c
.RI "typedef QList< ClanType > \fBbattle_for_rokugan::ClanTypeList\fP"
.br
.ti -1c
.RI "typedef SecretObjectiveType \fBbattle_for_rokugan::SOT\fP"
.br
.ti -1c
.RI "typedef CombatTokenType \fBbattle_for_rokugan::CTT\fP"
.br
.ti -1c
.RI "typedef StatusTokenType \fBbattle_for_rokugan::STT\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBbattle_for_rokugan::BorderType\fP "
.br
.RI "The BorderType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::CardType\fP "
.br
.RI "The CardType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::ClanType\fP "
.br
.RI "The ClanType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::PlaceType\fP "
.br
.RI "The PlaceType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::Phase\fP : unsigned char "
.br
.RI "The Phase enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::SecretObjectiveType\fP : unsigned char "
.br
.RI "The SecretObjectiveType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::ProvinceTokenType\fP "
.br
.RI "The ProvinceTokenType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::TerritoryType\fP : uchar "
.br
.RI "The TerritoryType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::CombatTokenType\fP "
.br
.RI "The CombatTokenType enum\&. "
.ti -1c
.RI "enum \fBbattle_for_rokugan::StatusTokenType\fP "
.br
.RI "The StatusTokenType enum\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
