.TH "lib_bfr/include/bfrLib.h" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/bfrLib.h
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/handler/battle\&.h'\fP
.br
\fC#include 'lib_bfr/handler/stats\&.h'\fP
.br
\fC#include 'lib_bfr/handler/turn\&.h'\fP
.br
\fC#include 'lib_bfr/karta/border\&.h'\fP
.br
\fC#include 'lib_bfr/karta/map\&.h'\fP
.br
\fC#include 'lib_bfr/karta/province\&.h'\fP
.br
\fC#include 'lib_bfr/karta/territory\&.h'\fP
.br
\fC#include 'lib_bfr/karta/tokenBasement\&.h'\fP
.br
\fC#include 'lib_bfr/object/card\&.h'\fP
.br
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_bfr/object/secretObjective\&.h'\fP
.br
\fC#include 'lib_bfr/token/combat\&.h'\fP
.br
\fC#include 'lib_bfr/token/control\&.h'\fP
.br
\fC#include 'lib_bfr/token/honor\&.h'\fP
.br
\fC#include 'lib_bfr/token/province\&.h'\fP
.br
\fC#include 'lib_bfr/game\&.h'\fP
.br
\fC#include 'bfrEnum\&.h'\fP
.br
\fC#include 'bfrLib_pre\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
