.TH "lib_bfr/include/lib_bfr/object/card.h" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/lib_bfr/object/card.h
.SH SYNOPSIS
.br
.PP
\fC#include 'bfrLib_pre\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbattle_for_rokugan::object::Card\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CardType \fBbattle_for_rokugan::operator+\fP (CardType type, uint i)"
.br
.ti -1c
.RI "CardType \fBbattle_for_rokugan::operator+\fP (CardType card, ClanType clan)"
.br
.ti -1c
.RI "CardType \fBbattle_for_rokugan::operator\-\fP (CardType left, CardType right)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
