.TH "lib_bfr/src/object/card.cpp" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/object/card.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/object/card\&.h'\fP
.br
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_baseAF/afFunction\&.h'\fP
.br
\fC#include 'lib_bfr/karta/province\&.h'\fP
.br
\fC#include 'lib_bfr/token/combat\&.h'\fP
.br
\fC#include 'lib_bfr/token/province\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "CardType \fBbattle_for_rokugan::operator+\fP (CardType type, uint i)"
.br
.ti -1c
.RI "CardType \fBbattle_for_rokugan::operator\-\fP (CardType left, CardType right)"
.br
.ti -1c
.RI "CardType \fBbattle_for_rokugan::operator+\fP (CardType card, ClanType clan)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
