.TH "lib_bfr/include/lib_bfr/object/clan.h" 3 "Wed Apr 7 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/lib_bfr/object/clan.h
.SH SYNOPSIS
.br
.PP
\fC#include 'bfrLib_pre\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbattle_for_rokugan::object::Clan\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ClanType \fBbattle_for_rokugan::operator+\fP (ClanType type, uint i)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
