.TH "lib_bfr/src/object/clan.cpp" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/object/clan.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_bfr/token/combat\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ClanType \fBbattle_for_rokugan::operator+\fP (ClanType type, uint i)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
