.TH "lib_bfr/src/token/control.cpp" 3 "Wed Apr 7 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/token/control.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'token/control\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
