.TH "lib_bfr/src/game.cpp" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/game.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'AFbase/AfFunction'\fP
.br
\fC#include 'lib_bfr/game\&.h'\fP
.br
\fC#include 'lib_bfr/handler/battle\&.h'\fP
.br
\fC#include 'lib_bfr/handler/stats\&.h'\fP
.br
\fC#include 'lib_bfr/handler/turn\&.h'\fP
.br
\fC#include 'lib_bfr/karta/map\&.h'\fP
.br
\fC#include 'lib_bfr/object/card\&.h'\fP
.br
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_bfr/object/secretObjective\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
