.TH "app/main.cpp" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <AFquick/AfGuiApplication>\fP
.br
\fC#include <TrinnGui>\fP
.br
\fC#include <QtGui/QIcon>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include 'AFbaseLib'\fP
.br
\fC#include 'BFRlib'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 8 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
