.TH "lib_bfr/src/karta/map.cpp" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/karta/map.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'AFbase/AfFunction'\fP
.br
\fC#include 'lib_bfr/karta/border\&.h'\fP
.br
\fC#include 'lib_bfr/karta/map\&.h'\fP
.br
\fC#include 'lib_bfr/karta/province\&.h'\fP
.br
\fC#include 'lib_bfr/karta/territory\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
