.TH "lib_bfr/src/object/player.cpp" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/object/player.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'handler/stats\&.h'\fP
.br
\fC#include 'handler/turn\&.h'\fP
.br
\fC#include 'karta/map\&.h'\fP
.br
\fC#include 'karta/province\&.h'\fP
.br
\fC#include 'karta/territory\&.h'\fP
.br
\fC#include 'object/card\&.h'\fP
.br
\fC#include 'object/clan\&.h'\fP
.br
\fC#include 'object/player\&.h'\fP
.br
\fC#include 'object/secretObjective\&.h'\fP
.br
\fC#include 'token/combat\&.h'\fP
.br
\fC#include <AfFunction>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
