.TH "lib_bfr/include/lib_bfr/object/player.h" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/lib_bfr/object/player.h
.SH SYNOPSIS
.br
.PP
\fC#include 'bfrLib_pre\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbattle_for_rokugan::object::Player\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
