.TH "lib_bfr/src/token/province.cpp" 3 "Wed Apr 7 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/token/province.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_bfr/token/province\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
