.TH "lib_bfr/src/object/secretObjective.cpp" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/object/secretObjective.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include <AFbase/AfFunction>\fP
.br
\fC#include 'lib_bfr/handler/stats\&.h'\fP
.br
\fC#include 'lib_bfr/karta/map\&.h'\fP
.br
\fC#include 'lib_bfr/karta/province\&.h'\fP
.br
\fC#include 'lib_bfr/karta/territory\&.h'\fP
.br
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include 'lib_bfr/object/player\&.h'\fP
.br
\fC#include 'lib_bfr/object/secretObjective\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SecretObjectiveType \fBbattle_for_rokugan::operator+\fP (SecretObjectiveType type, uint i)"
.br
.ti -1c
.RI "SecretObjectiveType \fBbattle_for_rokugan::operator++\fP (SecretObjectiveType type)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
