.TH "lib_bfr/src/handler/stats.cpp" 3 "Thu Mar 25 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/handler/stats.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/handler/stats\&.h'\fP
.br
\fC#include 'lib_bfr/karta/map\&.h'\fP
.br
\fC#include 'lib_bfr/object/clan\&.h'\fP
.br
\fC#include <set>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef bfr::handler::Stats::OneStat \fBBCO\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef bfr::handler::Stats::OneStat \fBBCO\fP"

.PP
Definition at line 115 of file stats\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
