.TH "lib_bfr/include/lib_bfr/karta/territory.h" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/include/lib_bfr/karta/territory.h
.SH SYNOPSIS
.br
.PP
\fC#include 'bfrLib_pre\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbattle_for_rokugan::karta::Territory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbattle_for_rokugan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "TerritoryType \fBbattle_for_rokugan::operator+\fP (TerritoryType type, unsigned i)"
.br
.ti -1c
.RI "TerritoryType \fBbattle_for_rokugan::operator++\fP (TerritoryType type)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
