.TH "lib_bfr/src/karta/tokenBasement.cpp" 3 "Fri Mar 26 2021" "Battle for rokugan" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_bfr/src/karta/tokenBasement.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_bfr/karta/tokenBasement\&.h'\fP
.br
\fC#include 'lib_bfr/token/combat\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Battle for rokugan from the source code\&.
